version: "3"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/airbnb
    depends_on:
      - mongo

  mongo:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=2000
      - MONGO_INITDB_DATABASE=airbnb
